import { useEffect, useState } from 'react'
import { Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Camera, Check, ChevronDown, Compass, Crown, Globe, Menu, Minus, Plus, QrCode, ShoppingBag, Stamp, X } from 'lucide-react'
import { api } from './services/api'
import { AuthUser, currentUser, login, logout, register } from './services/authService'
import QrScanner from './components/QrScanner'

type Story = { id: number; slug: string; title: string; category: string; readingTime: number; coverImage: string; summary: string }
type Product = { id: number; name: string; slug: string; price: number; thumbnailUrl: string; description: string }
const money = (value: number) => new Intl.NumberFormat('vi-VN').format(value) + 'đ'
const getStories = () => api.get<{ data: Story[] }>('/stories').then(response => response.data.data)
const getProduct = () => api.get<{ data: Product[] }>('/products').then(response => response.data.data[0])
function useProduct() { const [product, setProduct] = useState<Product>(); useEffect(() => { getProduct().then(setProduct).catch(() => undefined) }, []); return product }

function Shell({ children, cartCount, user, onLogout }: { children: React.ReactNode; cartCount: number; user?: AuthUser; onLogout: () => void }) {
    const [open, setOpen] = useState(false)
    const location = useLocation()
    return <div className="app-shell">
        <header className="topbar">
            <Link to="/" className="brand"><span className="brand-mark">MS</span><span>MEKONG<br /><b>STORY BOX</b></span></Link>
            <nav className={open ? 'nav open' : 'nav'}>
                <Link className={location.pathname === '/' ? 'active' : ''} to="/">Trang chủ</Link><Link to="/story-box">Story Box</Link><Link to="/stories">Câu chuyện</Link><Link to="/passport">Digital Passport</Link><Link to="/about">Về chúng tôi</Link>
            </nav>
            <div className="header-actions"><button className="language">VI <ChevronDown size={14} /></button>{user ? <button className="user-action" onClick={onLogout}>{user.fullName} · Thoát</button> : <Link className="user-action" to="/login">Đăng nhập</Link>}<Link aria-label="Giỏ hàng" className="icon-btn cart-link" to="/cart"><ShoppingBag size={19} />{cartCount > 0 && <span>{cartCount}</span>}</Link><button className="menu-btn" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div>
        </header>{children}
        <footer><div><Link className="brand footer-brand" to="/"><span className="brand-mark">MS</span><span>MEKONG<br /><b>STORY BOX</b></span></Link><p>Một chuyến về miền Tây,<br />nằm trong một chiếc hộp.</p></div><div><strong>Khám phá</strong><Link to="/story-box">Story Box</Link><Link to="/stories">Câu chuyện</Link><Link to="/passport">Digital Passport</Link></div><div><strong>Theo dõi hành trình</strong><p className="social"><Globe size={18} /><Globe size={18} /></p><small>© 2024 Mekong Story Box</small></div></footer>
    </div>
}

function Home({ addToCart }: { addToCart: () => void }) {
    const navigate = useNavigate(); const [stories, setStories] = useState<Story[]>([]); const [product, setProduct] = useState<Product>(); useEffect(() => { getStories().then(setStories).catch(() => setStories([])); getProduct().then(setProduct).catch(() => undefined) }, []); return <main>
        <section className="hero"><div className="hero-copy"><p className="eyebrow"><span /> CULTURAL EXPERIENCE PLATFORM</p><h1>Một chuyến về<br /><em>miền Tây,</em><br />nằm trong một chiếc hộp.</h1><p className="hero-lead">Khám phá hương vị, câu chuyện và ký ức miền sông nước — theo một cách hoàn toàn mới.</p><div className="button-row"><button className="button primary" onClick={() => navigate('/story-box')}>Khám phá Story Box <ArrowRight size={17} /></button><button className="text-button" onClick={() => navigate('/experience')}><QrCode size={17} /> Trải nghiệm miền Tây</button></div></div><div className="hero-art"><div className="sun" /><div className="water" /><div className="leaf leaf-one">✦</div><div className="box-visual"><div className="box-label"><span>MEKONG</span><b>STORY<br />BOX</b><small>CAN THO · 001</small></div></div><span className="art-note note-one">stories<br />from the river</span><span className="art-note note-two">est. 2024</span></div><div className="hero-scroll">SCROLL TO EXPLORE <ArrowRight size={14} /></div></section>
        <section className="intro section-wrap"><div className="section-kicker">01 / THE IDEA</div><div className="intro-grid"><h2>Bạn không mua<br />một chiếc hộp.<br /><em>Bạn mua một câu chuyện.</em></h2><div><p className="large-copy">Story Box là một chuyến du lịch miền Tây thu nhỏ — nơi mỗi món quà mở ra một vùng đất, một người làm ra nó, và một ký ức đáng được kể.</p><Link className="under-link" to="/about">Tìm hiểu câu chuyện của chúng tôi <ArrowRight size={15} /></Link></div></div><div className="steps">{[['01', 'UNBOX', 'Mở hộp và khám phá những món quà từ miền Tây.'], ['02', 'SCAN', 'Quét QR để bước vào trải nghiệm số.'], ['03', 'DISCOVER', 'Khám phá câu chuyện phía sau từng món quà.']].map(([n, t, d]) => <div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
        {product && <section className="featured section-wrap"><div className="section-kicker">02 / THE FIRST JOURNEY</div><div className="featured-grid"><div className="product-photo"><img src={product.thumbnailUrl} alt={product.name} /><span className="photo-stamp">CẦN THƠ<br />#001</span></div><div className="product-info"><p className="eyebrow">{product.name}</p><h2>Nhịp sống<br /><em>trên sông Hậu.</em></h2><p>{product.description}</p><div className="product-meta"><strong>{money(product.price)}</strong><span>6 món quà · 1 hành trình</span></div><button className="button dark" onClick={addToCart}>Thêm vào giỏ <ShoppingBag size={16} /></button><Link className="under-link" to="/story-box">Xem chi tiết sản phẩm <ArrowRight size={15} /></Link></div></div></section>}
        <section className="stories-band"><div className="section-wrap"><div className="band-heading"><div><div className="section-kicker">03 / FROM THE DELTA</div><h2>Những câu chuyện<br /><em>đáng để mang về.</em></h2></div><Link className="under-link light-link" to="/stories">Xem tất cả câu chuyện <ArrowRight size={15} /></Link></div><div className="story-grid">{stories.slice(0, 3).map(story => <StoryCard story={story} key={story.id} />)}</div></div></section>
    </main>
}

function StoryCard({ story }: { story: Story }) { return <Link to={'/stories/' + story.slug} className="story-card"><div className="story-image"><img src={story.coverImage} alt={story.title} /><span>{story.category}</span></div><div className="story-card-body"><small>{story.readingTime} phút đọc</small><h3>{story.title}</h3><p>{story.summary}</p><ArrowRight size={17} /></div></Link> }
function StoryBox({ addToCart }: { addToCart: () => void }) { const [product, setProduct] = useState<Product>(); useEffect(() => { getProduct().then(setProduct).catch(() => undefined) }, []); return <main className="page"><div className="page-hero"><p className="eyebrow">THE STORY BOX / CẦN THƠ #001</p><h1>Một miền sông nước<br /><em>để mang về.</em></h1><p>Đằng sau mỗi món quà là một vùng đất, một người làm ra nó, và một câu chuyện đáng được kể.</p></div>{product && <section className="product-detail section-wrap"><div className="product-photo large"><img src={product.thumbnailUrl} alt={product.name} /><span className="photo-stamp">CẦN THƠ<br />#001</span></div><div className="detail-copy"><span className="number-label">01 / INSIDE THE BOX</span><h2>Chiếc hộp chỉ là<br /><em>điểm bắt đầu.</em></h2><p>{product.description}</p><div className="inside-list">{['Cần Thơ Postcard', 'Mekong Map', 'Local Snack', 'Handmade Souvenir', 'Cultural Story Card', 'Digital Passport Card'].map((x, i) => <div key={x}><b>0{i + 1}</b><span>{x}</span><ArrowRight size={15} /></div>)}</div><div className="buy-line"><strong>{money(product.price)}</strong><button className="button dark" onClick={addToCart}>Bắt đầu hành trình <ArrowRight size={16} /></button></div></div></section>}</main> }
function Stories() { const [stories, setStories] = useState<Story[]>([]); useEffect(() => { getStories().then(setStories).catch(() => setStories([])) }, []); return <main className="page"><div className="page-hero compact"><p className="eyebrow">THE MEKONG JOURNAL</p><h1>Những điều<br /><em>miền Tây kể.</em></h1><p>Chậm rãi một chút. Lắng nghe kỹ hơn. Mỗi câu chuyện là một cánh cửa nhỏ dẫn về miền sông nước.</p></div><section className="section-wrap journal"><div className="filters"><span>ALL STORIES</span>{['FOOD', 'PEOPLE', 'PLACES', 'CRAFTS', 'MUSIC', 'LIFESTYLE'].map(x => <button key={x}>{x}</button>)}</div><div className="journal-grid">{stories.map(story => <StoryCard story={story} key={story.id} />)}</div></section></main> }
function Experience() { const navigate = useNavigate(); return <main className="experience"><div className="experience-card"><div className="qr-orbit"><QrCode size={54} /><span>SCAN</span></div><p className="eyebrow">YOUR DIGITAL JOURNEY</p><h1>Chiếc hộp chỉ là<br /><em>điểm bắt đầu.</em></h1><p>Quét mã QR trên thẻ Digital Passport để mở khóa câu chuyện đầu tiên của bạn.</p><button className="button primary" onClick={() => navigate('/scan')}><Camera size={17} /> Mở camera để scan QR <ArrowRight size={17} /></button><small>Camera permission required · HTTPS hoặc localhost</small></div></main> }
function QRExperience() { const [done, setDone] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const { token } = useParams(); const navigate = useNavigate(); const verify = async () => { setLoading(true); setError(''); try { const response = await api.post<{ data: { valid: boolean } }>('/qr/verify', { token }); if (response.data.data.valid) setDone(true); else setError('QR code không hợp lệ hoặc đã bị vô hiệu hóa.'); } catch { setError('Vui lòng đăng nhập trước khi scan QR.'); } finally { setLoading(false); } }; return <main className="experience qr-page"><div className="journey-card">{!done ? <><div className="success-icon"><QrCode size={31} /></div><p className="eyebrow">QR VERIFICATION / CẦN THƠ #001</p><h1>Your Mekong<br /><em>journey begins.</em></h1><p>Mã QR đã sẵn sàng mở ra một câu chuyện từ chợ nổi Cái Răng.</p>{error && <><p role="alert">{error}</p><Link className="under-link" to="/login">Đăng nhập để tiếp tục <ArrowRight size={15} /></Link></>}<button className="button dark" onClick={verify} disabled={loading}>{loading ? 'Đang xác thực...' : 'Xác thực QR'} <Check size={17} /></button></> : <><div className="success-icon"><Check size={31} /></div><p className="eyebrow">EXPERIENCE UNLOCKED</p><h1>Chào mừng bạn<br /><em>về miền Tây.</em></h1><p>Lần khám phá đã được ghi vào Digital Passport của bạn.</p><div className="reward"><Stamp size={20} /><span>EXPERIENCE COUNTED</span><strong>+100 điểm</strong></div><button className="button dark" onClick={() => navigate('/passport')}>Mở Digital Passport <ArrowRight size={17} /></button></>}</div></main> }
function Passport() { const [passport, setPassport] = useState<{ totalPoints: number; level: number; explorationCount: number }>(); const [error, setError] = useState(false); useEffect(() => { api.get<{ data: typeof passport }>('/passport').then(response => setPassport(response.data.data)).catch(() => setError(true)) }, []); const points = passport?.totalPoints ?? 0; const count = passport?.explorationCount ?? 0; return <main className="page passport-page"><div className="passport-head section-wrap"><div><p className="eyebrow">YOUR COLLECTIBLE JOURNEY</p><h1>Digital<br /><em>Passport.</em></h1></div><div className="level-mark"><Crown size={19} /><span>LEVEL {passport?.level ?? 1}</span><strong>{count ? 'MEKONG EXPLORER' : 'READY TO EXPLORE'}</strong></div></div><section className="passport-paper section-wrap"><div className="passport-top"><span>MEKONG STORY BOX</span><span>EXPLORATIONS {count}</span></div><div className="passport-main"><div className="passport-avatar"><Compass size={42} /><small>EXPLORER</small></div><div><p className="eyebrow">{error ? 'SIGN IN TO CONTINUE' : count ? 'YOUR JOURNEY SO FAR' : 'YOUR JOURNEY STARTS HERE'}</p><h2>{count ? <>Your story<br /><em>is growing.</em></> : <>Your passport<br /><em>is waiting.</em></>}</h2><div className="points"><strong>{points.toLocaleString('vi-VN')}</strong><span>POINTS EARNED</span></div></div></div><div className="progress-label"><span>YOUR PROGRESS</span><span>{count} EXPLORATIONS</span></div><div className="progress"><span style={{ width: `${Math.min(count * 20, 100)}%` }} /></div><div className="badge-row"><div className={'passport-badge ' + (count ? 'unlocked' : 'locked')}><span>🛶</span><b>Floating Market</b><small>{count ? 'UNLOCKED' : 'LOCKED'}</small></div><div className="passport-badge locked"><span>🌿</span><b>Mekong Garden</b><small>LOCKED</small></div><div className="passport-badge locked"><span>🎵</span><b>Southern Music</b><small>LOCKED</small></div><div className="passport-badge locked"><span>🍜</span><b>Mekong Cuisine</b><small>LOCKED</small></div></div></section></main> }
function Cart({ count, setCount }: { count: number; setCount: (n: number) => void }) { const navigate = useNavigate(); const product = useProduct(); if (!product) return <main className="page"><div className="section-wrap"><p className="eyebrow">YOUR JOURNEY / CART</p><h1>Đang tải<br /><em>hành trình.</em></h1></div></main>; return <main className="page cart-page"><div className="section-wrap"><p className="eyebrow">YOUR JOURNEY / CART</p><h1>Chuẩn bị<br /><em>lên đường.</em></h1><div className="cart-layout"><div className="cart-item"><img src={product.thumbnailUrl} alt={product.name} /><div><span>{product.name}</span><h3>Cần Thơ #001</h3><small>6 món quà · Digital experience</small><div className="quantity"><button onClick={() => setCount(Math.max(0, count - 1))}><Minus size={14} /></button><b>{count}</b><button onClick={() => setCount(count + 1)}><Plus size={14} /></button></div></div><strong>{money(product.price * count)}</strong></div><div className="summary"><span>TỔNG ĐƠN HÀNG</span><div><b>Tạm tính</b><strong>{money(product.price * count)}</strong></div><div><b>Vận chuyển</b><strong>Miễn phí</strong></div><hr /><div className="total"><b>Tổng cộng</b><strong>{money(product.price * count)}</strong></div><button className="button dark full" onClick={() => navigate('/checkout')}>Tiến hành đặt hàng <ArrowRight size={16} /></button></div></div></div></main> }
function Checkout() { const [sent, setSent] = useState(false); return <main className="page"><div className="section-wrap checkout"><p className="eyebrow">FINAL STEP / CHECKOUT</p>{sent ? <div className="order-success"><div className="success-icon"><Check /></div><h1>Đơn hàng đã<br /><em>được ghi nhận.</em></h1><p>Cảm ơn bạn đã chọn mang một phần miền Tây về nhà. Mã đơn hàng của bạn là <b>MSB-24001</b>.</p><Link className="button dark" to="/passport">Về Digital Passport <ArrowRight size={16} /></Link></div> : <><h1>Đưa câu chuyện<br /><em>về nhà.</em></h1><form onSubmit={e => { e.preventDefault(); setSent(true) }}><label>HỌ VÀ TÊN<input required placeholder="Nguyễn Minh Linh" /></label><label>SỐ ĐIỆN THOẠI<input required placeholder="09xx xxx xxx" /></label><label>ĐỊA CHỈ NHẬN HÀNG<textarea required placeholder="Số nhà, đường, phường/xã, tỉnh/thành phố" /></label><button className="button dark" type="submit">Xác nhận đặt hàng <ArrowRight size={16} /></button></form></>}</div></main> }
function About() { return <main className="page about"><div className="page-hero compact"><p className="eyebrow">OUR WHY</p><h1>Có một miền Tây<br /><em>luôn ở trong tim.</em></h1><p>Chúng tôi kể những câu chuyện văn hóa bằng ngôn ngữ của thế hệ hôm nay.</p></div><div className="section-wrap about-copy"><p className="large-copy">Mekong Story Box được bắt đầu bởi những người trẻ lớn lên bên dòng sông, nhưng đôi khi quên mất cách lắng nghe nó.</p><p>Chúng tôi tin rằng văn hóa không nằm yên trong bảo tàng. Văn hóa ở trong tiếng máy ghe lúc 5 giờ sáng, trong vị ngọt của trái dừa, trong những bàn tay khéo léo và trong cách một câu chuyện được truyền từ người này sang người khác.</p></div></main> }
function AuthPage({ mode, onAuthenticated }: { mode: 'login' | 'register'; onAuthenticated: (user: AuthUser) => void }) { const navigate = useNavigate(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); try { const user = mode === 'login' ? await login(String(form.get('email')), String(form.get('password'))) : await register(String(form.get('fullName')), String(form.get('email')), String(form.get('password'))); onAuthenticated(user); navigate('/'); } catch { setError(mode === 'login' ? 'Email hoặc mật khẩu không đúng.' : 'Không thể tạo tài khoản. Email có thể đã được sử dụng.'); } finally { setLoading(false); } }; return <main className="page auth-page"><div className="auth-card"><p className="eyebrow">MEKONG STORY BOX / ACCOUNT</p><h1>{mode === 'login' ? <>Chào mừng<br /><em>trở lại.</em></> : <>Bắt đầu<br /><em>hành trình.</em></>}</h1><form onSubmit={submit}>{mode === 'register' && <label>HỌ VÀ TÊN<input name="fullName" required maxLength={150} placeholder="Nguyễn Minh Linh" /></label>}<label>EMAIL<input name="email" type="email" required placeholder="you@example.com" /></label><label>MẬT KHẨU<input name="password" type="password" required minLength={8} placeholder="Tối thiểu 8 ký tự" /></label>{error && <p role="alert">{error}</p>}<button className="button dark" disabled={loading}>{loading ? 'Đang xử lý...' : mode === 'login' ? 'Đăng nhập' : 'Đăng ký'} <ArrowRight size={16} /></button></form><p className="auth-switch">{mode === 'login' ? 'Chưa có tài khoản?' : 'Đã có tài khoản?'} <Link to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Đăng ký' : 'Đăng nhập'}</Link></p></div></main> }
function Admin() { return <main className="page admin"><div className="section-wrap"><p className="eyebrow">ADMIN / OVERVIEW</p><h1>Good morning,<br /><em>storyteller.</em></h1><div className="metric-grid">{[['1,248', 'TOTAL USERS'], ['86', 'ORDERS'], ['25.7m', 'REVENUE'], ['312', 'QR SCANS']].map(([v, l]) => <div className="metric" key={l}><strong>{v}</strong><span>{l}</span><small>+12.4% this month</small></div>)}</div><div className="admin-table"><div><strong>Recent QR activity</strong><span>VIEW ALL <ArrowRight size={14} /></span></div>{['Cần Thơ #001 · token-8af2', 'Floating Market · token-3c19', 'Mekong Garden · token-91ad'].map((x, i) => <p key={x}><QrCode size={16} /><span>{x}</span><b className={i === 2 ? 'revoked' : ''}>{i === 2 ? 'REVOKED' : 'ACTIVE'}</b></p>)}</div></div></main> }

export default function App() { const [cartCount, setCartCount] = useState(0); const [user, setUser] = useState<AuthUser>(); useEffect(() => { if (localStorage.getItem('mekong_access_token')) currentUser().then(setUser).catch(() => localStorage.removeItem('mekong_access_token')) }, []); const addToCart = () => setCartCount(x => x + 1); const handleLogout = () => logout().then(() => setUser(undefined)); return <Shell cartCount={cartCount} user={user} onLogout={handleLogout}><Routes><Route path="/" element={<Home addToCart={addToCart} />} /><Route path="/story-box" element={<StoryBox addToCart={addToCart} />} /><Route path="/stories" element={<Stories />} /><Route path="/stories/:id" element={<Stories />} /><Route path="/experience" element={<Experience />} /><Route path="/scan" element={<QrScanner />} /><Route path="/experience/qr/:token" element={<QRExperience />} /><Route path="/passport" element={<Passport />} /><Route path="/cart" element={<Cart count={cartCount || 1} setCount={setCartCount} />} /><Route path="/checkout" element={<Checkout />} /><Route path="/about" element={<About />} /><Route path="/login" element={<AuthPage mode="login" onAuthenticated={setUser} />} /><Route path="/register" element={<AuthPage mode="register" onAuthenticated={setUser} />} /><Route path="/admin" element={<Admin />} /></Routes></Shell> }
